[package]
name = "dist-kv"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.108"

[[bin]]
name = "server"
path = "src/server.rs"

[[bin]]
name = "client"
path = "src/client.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html